/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Didier Aaron
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }
    
    public void listenMenu(ActionListener c)
    {
        mniExit.addActionListener(c);
        mniAbourt.addActionListener(c);
        mniUser.addActionListener(c);
        mniCreative.addActionListener(c);
        mniUser.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mniAbourt = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnModuls = new javax.swing.JMenu();
        mniUser = new javax.swing.JMenuItem();
        mniCreative = new javax.swing.JMenuItem();
        Tables = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuP.png"))); // NOI18N

        mnFile.setText("Info");

        mniAbourt.setText("About");
        mnFile.add(mniAbourt);

        mniExit.setText("Exit");
        mnFile.add(mniExit);

        jMenuBar2.add(mnFile);

        mnModuls.setText("Options");

        mniUser.setText("User Register");
        mniUser.setActionCommand("User");
        mnModuls.add(mniUser);

        mniCreative.setText("Creative Spaces Register");
        mniCreative.setActionCommand("Creative");
        mniCreative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreativeActionPerformed(evt);
            }
        });
        mnModuls.add(mniCreative);

        Tables.setText("Tables");
        Tables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablesActionPerformed(evt);
            }
        });
        mnModuls.add(Tables);

        jMenuBar2.add(mnModuls);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCreativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreativeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniCreativeActionPerformed

    private void TablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablesActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Tables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnModuls;
    private javax.swing.JMenuItem mniAbourt;
    private javax.swing.JMenuItem mniCreative;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniUser;
    // End of variables declaration//GEN-END:variables
}
