/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class FrmReport extends javax.swing.JFrame {

    /**
     * Creates new form FmUser
     */
    public FrmReport() {
        initComponents();
    }

    //JOptionPane en vista para no violentar el MVC
    public static void setMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public void setDataTable(String[][] data, String[] labels) {
        this.tblReport.setModel(new DefaultTableModel(data, labels));
        this.jScrollPane1.setViewportView(this.tblReport);
    }
    
    public String[] getRowSelected() {
        int rowSelect = this.tblReport.getSelectedRow();
        String[] rowData = new String[this.tblReport.getColumnCount()];
        if (rowSelect != -1) {
            for (int i = 0; i < rowData.length; i++) {
                rowData[i] = this.tblReport.getValueAt(rowSelect, i).toString();
            }
            return rowData;
        } else {
            return new String[0];
        }
    }
    
    public void listenMouse(MouseListener controller) {
        this.tblReport.addMouseListener(controller);
    }
    
    public void filterByID() {
        DefaultTableModel modelTable = (DefaultTableModel) this.tblReport.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelTable);
        this.tblReport.setRowSorter(sorter);
        String textSearch = this.txtFilterID.getText();
        if (textSearch.length() == 0) {
            sorter.setRowFilter(null);
            this.tblReport.clearSelection();
            
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(textSearch, 0));
        }
        
    }
    
    public void listenKey(KeyListener controller) {
        this.txtFilterID.addKeyListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFilterID = new javax.swing.JTextField();
        panelButton1 = new view.PanelButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Filter by ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFilterID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public PanelButton getPanelButton() {
        return this.panelButton1;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private view.PanelButton panelButton1;
    private javax.swing.JTable tblReport;
    private javax.swing.JTextField txtFilterID;
    // End of variables declaration//GEN-END:variables
}
