/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class FrmUser extends javax.swing.JFrame {

    /**
     * Creates new form FrameUser
     */
    public FrmUser() {
        initComponents();
    }
    
    public static void setMessage (String msg){
        JOptionPane.showMessageDialog(null, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton2 = new view.PanelButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(panelButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
        public PanelButton getPanelButton() {

        return this.panelButton2;

    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.PanelButton panelButton2;
    // End of variables declaration//GEN-END:variables
}
